spring.application.name=Monsteral
spring.datasource.url=jdbc:mysql://localhost:8080/clients
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
# Configuración de Hibernate para imprimir consultas SQL
logging.level.org.hibernate.SQL=DEBUG
#logging.level.root=DEBUG
